AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  GDoorClientAPI:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: ''
      MemorySize: 192
      Timeout: 30
      Role: 'arn:aws:iam::126281209629:role/service-role/GDoorClientApi'
      Environment:
        Variables:
          IOT_REGION: 'eu-west-1'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /user/createNewUser
            Method: POST
